Items = {
    pistol = {
        label = 'Pistol',
        weight = 1800,
        stack = 1,
        type = 'weapon',
        description = 'A standard pistol. Reliable and widely used.',
    },
    bandage = {
        label = 'Bandage',
        weight = 150,
        stack = 10,
        type = 'medical',
        description = 'Stops the bleeding.',
    },
    water_bottle = {
        label = 'Water Bottle',
        weight = 500,
        stack = 20,
        type = 'drink',
        description = 'A refreshing bottle of water.',
    },
    bread = {
        label = 'Bread',
        weight = 400,
        stack = 10,
        type = 'food',
        description = 'A fresh loaf of bread.',
    },
    phone = {
        label = 'Phone',
        weight = 200,
        stack = 1,
        type = 'item',
        description = 'Your trusty smartphone.',
    },
    radio = {
        label = 'Radio',
        weight = 1200,
        stack = 1,
        type = 'item',
        description = 'Two-way radio for staying in touch.',
    },
    repair_kit = {
        label = 'Repair Kit',
        weight = 2500,
        stack = 3,
        type = 'item',
        description = 'Patches up a damaged vehicle.',
    },
    lockpick_set = {
        label = 'Lockpick Set',
        weight = 600,
        stack = 3,
        type = 'item',
        description = "A set of tools for getting into places you shouldn't.",
    },
    medkit = {
        label = 'Medkit',
        weight = 2000,
        stack = 3,
        type = 'medical',
        description = 'Treats serious injuries.',
    },
    energy_drink = {
        label = 'Energy Drink',
        weight = 400,
        stack = 10,
        type = 'drink',
        description = 'A jolt of caffeine and sugar.',
    },
    chocolate_bar = {
        label = 'Chocolate Bar',
        weight = 300,
        stack = 10,
        type = 'food',
        description = 'A sweet snack.',
    },
    money_bag = {
        label = 'Money Bag',
        weight = 1000,
        stack = 5,
        type = 'item',
        description = 'A bag stuffed with cash.',
    },
    id_card = {
        label = 'ID Card',
        weight = 50,
        stack = 1,
        type = 'item',
        description = 'Government-issued identification.',
    },
    gold_chain = {
        label = 'Gold Chain',
        weight = 200,
        stack = 5,
        type = 'item',
        description = 'Worth a fair bit if you can find a buyer.',
    },
    hat = {
        label = 'Hat',
        weight = 200,
        stack = 1,
        type = 'item',
        description = 'Keeps the sun out of your eyes.',
    },
    gloves = {
        label = 'Gloves',
        weight = 250,
        stack = 1,
        type = 'item',
        description = 'Good for keeping your hands clean.',
    },
    ammo_9mm = {
        label = '9mm Ammo',
        weight = 10,
        stack = 100,
        type = 'ammo',
        description = 'Standard 9mm pistol ammunition.',
    },
    knife = {
        label = 'Knife',
        weight = 300,
        stack = 1,
        type = 'weapon',
        description = 'Sharp and dangerous in the wrong hands.',
    },
    zip_tie = {
        label = 'Zip Tie',
        weight = 50,
        stack = 20,
        type = 'item',
        description = 'Handy for restraining someone.',
    },
    cigarettes = {
        label = 'Cigarettes',
        weight = 50,
        stack = 20,
        type = 'item',
        description = "Bad for you, but you don't care.",
    },
    lighter = {
        label = 'Lighter',
        weight = 50,
        stack = 5,
        type = 'item',
        description = 'A reliable flame.',
    },
    burger = {
        label = 'Burger',
        weight = 400,
        stack = 10,
        type = 'food',
        description = 'Smells decent.',
    },
}
