Items = {
    water_bottle = {
        label = 'Water Bottle',
        weight = 500,
        stack = 20,
        type = 'drink',
        image = 'water_bottle.png',
        description = 'A refreshing bottle of water.',
    },
    sandwich = {
        label = 'Sandwich',
        weight = 300,
        stack = 20,
        type = 'food',
        image = 'sandwich.png',
        description = 'Smells decent.',
    },
    phone = {
        label = 'Phone',
        weight = 200,
        stack = 1,
        type = 'item',
        image = 'phone.png',
        description = 'Your trusty smartphone.',
    },
    lockpick = {
        label = 'Lockpick',
        weight = 100,
        stack = 5,
        type = 'item',
        image = 'lockpick.png',
        description = "Handy for getting into places you shouldn't.",
    },
    bandage = {
        label = 'Bandage',
        weight = 150,
        stack = 10,
        type = 'item',
        image = 'bandage.png',
        description = 'Stops the bleeding.',
    },
    money_bag = {
        label = 'Money Bag',
        weight = 1000,
        stack = 5,
        type = 'item',
        image = 'money_bag.png',
        description = 'A bag stuffed with cash.',
    },
}
